### ISSUE TITLE
Certain special characters are shown as HTML entities

### ISSUE THREAD

**Issue by drpfenderson** [GezimSejdiu/Rocket.Chat-Trello-Integration#3]
A number of special characters that are in Trello titles, descriptions, comments, etc all show as their HTML reference entities instead of the characters themselves.

Examples would be `& " ' < >` all show as `&amp; &quot; &#39 &lt; &gt;` respectively. Characters like `^ % # ! ? +` are all escaped properly.

Screenshot:
![image](https://user-images.githubusercontent.com/7515881/40672345-62bbbf48-6323-11e8-9601-a15c1fe73b0c.png)

**Comment by GezimSejdiu** [comment]
Hi @drpfenderson ,
many thanks for opening the issue. I somehow missed it and just saw it today. In order to see the behavior of it, I tried to reproduce it and got this result (I checked it on the web and RC client for Linux v2.11.0 on Rocket.Chat version 0.66.1):
 
![special_characters_trelloissue](https://user-images.githubusercontent.com/5259296/42380162-3bb151ba-812d-11e8-91db-3d73362d68df.png)

To me this presentation lookw fine, right? Could you please, double check it and let me know if the issue still persist.

Best regards,

**Comment by GezimSejdiu** [comment]
Hi @drpfenderson ,
any news about the issue? Is this happening again, if so, could you let me know that I can double check it once more?
