### ISSUE TITLE
Project active? Possibility to integrate with Restyaboard?

### ISSUE THREAD

**Issue by schultzglen87** [GezimSejdiu/Rocket.Chat-Trello-Integration#5]
Looks like this project is not active. Is it easy to integrate
Restyaboard instead of Trello?

**Comment by GezimSejdiu** [comment]
Hi @schultzglen87 ,

many thanks for your message. There is only one feature request #4 which is quite useful when you want to get rid of some notification which may not be too important and rather focus on main points. I will try to find some time and work on that, but otherwise, we are using the integration already on our RC instance. So, I assume we can still consider the project as _active_.

Reg. your suggestion about Restyaboard. I think there is no direct integration between this one --> RC--> Restyaboard. Usually, you have to create your own integration as described on RC docs : https://rocket.chat/docs/administrator-guides/integrations/ and then make this integration with the Restyaboard. I haven't use Restyaboard myself, but I did use [wekan](https://wekan.github.io/) (and kind of like it :) ) and I also did a basic integration but will try to find some time to publish it as integration with Rocket.Chat.

Feel free to write to me in case there is something I can help you out with the integration.

Best regards,

**Comment by schultzglen87** [comment]
@GezimSejdiu Thanks for your reply. Glad to know the project is active.

Tried Wekan, but didn't like it though:-( And so switched to
Restyaboard. Will check the doc and get back to you if required.
Thanks again.

**Comment by GezimSejdiu** [comment]
Great! Let me know in case I can also help there.

Best,
